REAL_TOT      = 'Total transaction'
REAL_TOT_EXP  = 'Dépense totale'
REAL_TOT_INC  = 'Revenue totale'
REAL_TOT_REAL = 'Total réelle'
REAL_TOT_REAL_EXP = 'Dépense réelle'
REAL_TOT_REAL_INC = 'Revenue réel'
REAL_C1_TOT = "Total"
REAL_C1_TOT_PLUS = "Total +"
REAL_C1_TOT_MOINS = "Total -"
REAL_TOT_TITLE_MONTHLY = "Total Mensuel"
REAL_TOT_TITLE_PDF = "Total Relevé"

INIT_DATE = "Date"
INIT_SOLD_ST = "Start"
INIT_TITLE_BILAN = "End"
INIT_TITLE_IN = "Income"
INIT_TITLE_LOS = "Loss"
INIT_VALID = "Validation"
INIT_DETAIL = ""
INIT_TITLE_EXPECTED = 'Expected'
INIT_TITLE_REAL = 'Real'
INIT_TITLE_TOT = 'Total'
INIT_TITLE_NAME = 'Name'
INIT_TITLE_VALIDITY = 'Validity'
INIT_TITLE_EXTRACTION = 'Extraction'
INIT_TITLE_IDENTIFICATION = 'Identification'
INIT_TITLE_REALISATION = 'Realisation'
INIT_TITLE_PATH = 'Path'
INIT_TITLE_DATE= 'Date'
INIT_VALID_TOT_NOTE = "Valid if the difference <50€ [for small amout] or <10% of the max [for large amout]"
INIT_TAB_COL_CAT1 = "Categorie 1 "
INIT_TAB_COL_CAT2 = "Categorie 2 "
INIT_TAB_COL_TYPE = "Type"
INIT_TAB_COL_REFUND = "Remb. Prévu"
INIT_TAB_COL_NAME = "Nom"
INIT_TAB_COL_VALUE = "Valeur"

DATA_VAL_ERROR_INTERN_TITLE = "Invalid input"
DATA_VAL_ERROR_INTERN_MSG = "Please enter a valid input"
DATA_VAL_ERROR_SHARE_TITLE = "Invalid input"
DATA_VAL_ERROR_SHARE_MSG = "Please enter a valid number"